Release/v2.0
ThundeRatz/vss_simulation pull request #11
Opened 2020-10-05 02:24 UTC by FelipeGdM

List changes of #8 and #9

2020-10-05 02:31 UTC, LucasHaug requested changes

2020-10-05 02:31 UTC, LucasHaug commented on CHANGELOG.md
>  - Comportamento dos motores ideal demais - longe da realidade
Aqui ficou em português

2020-10-05 03:54 UTC, lucastrschneider commented
Nos dois READMEs, na parte de dependências, quando mostra o que instalar com o apt, ainda ta python-pygame. Acho que tinha que ser python3-pygame, igual ta nas dependências do package.xml
~eu to no cel, se n ja mudava logo~

2020-10-05 04:19 UTC, d-nery requested changes

2020-10-05 04:19 UTC, d-nery commented on CHANGELOG.md
> +## v2.0.0
Você deveria linkar os títulos das versões às tags do GitHub (mesmo que ela não exista ainda, pra quando mergear e vc criar a tag, ele mandar pra lá). Aqui tem um guideline de changelog: https://keepachangelog.com/en/1.0.0/

Aí tem um padrãozinho de sessões e mostra como faz o link que eu falei

2020-10-07 13:30 UTC, LucasHaug approved these changes

2020-10-07 13:37 UTC, d-nery approved these changes

2020-10-07 13:37 UTC, d-nery commented on CHANGELOG.md
> +## [2.0.0] - 2020-10-05 - [Open Camera](https://github.com/ThundeRatz/vss_simulation/releases/tag/v2.0)
Só uma coisa, os colchetes em volta da versão é justamente pra virar um link de diff com a versão anterior, se vc olhar lá no exemplo tem (mas ele põe o link no fim do documento, pra ficar menos cheio aqui), não seria pra ter colchetes literalmente em volta da versão, mas enfim, isso não vai fazer grandes diferenças até pq vxc já linkou pra release em si, mas só avisando

2020-10-07 14:07 UTC, merged